screen =
    object
        "height" : 0
        "width"  : 0
        "pixels" : (list)

resize =
    fn (&screen new-height new-width)
        &h = (&screen "height")
        &w = (&screen "width")

        &h = new-height
        &w = new-width

        &p = (&screen "pixels")

        n = (&h * &w)

        while ((len &p) > n)
            pop &p
            nil

        while ((len &p) < n)
            append &p 0x303030
            nil

set-pixel =
    fn (&screen row col color)
        &w = (&screen "width")

        idx = ((&w * row) + col)
        ((&screen "pixels") idx) = color

display =
    fn (&screen)
        &h = (&screen "height")
        &w = (&screen "width")
        &p = (&screen "pixels")

        r = 0
        while (r < &h)
            c = 0
            while (c < &w)
                idx = ((r * &w) + c)
                print " "
                print (num-fmt "06x" (&p idx))
                c += 1
            print "\n"
            r += 1

rgb-to-term-fg =
    fn (&rgb)
#         r = ((&rgb & 0xff0000) >> 16)
#         g = ((&rgb & 0x00ff00) >> 8)
#         b =  (&rgb & 0x0000ff)

#         fmt "\e[38;2;%;%;%m"
#             num-fmt "d" r
#             num-fmt "d" g
#             num-fmt "d" b
        "\e[48;2;255;0;0m"

rgb-to-term-bg =
    fn (&rgb)
#         r = ((&rgb & 0xff0000) >> 16)
#         g = ((&rgb & 0x00ff00) >> 8)
#         b =  (&rgb & 0x0000ff)

        "\e[48;2;255;0;0m"
#         fmt "\e[48;2;%;%;%m"
#             num-fmt "d" r
#             num-fmt "d" g
#             num-fmt "d" b

display-real =
    fn (&screen)
        &h = (&screen "height")
        &w = (&screen "width")
        &p = (&screen "pixels")

        r = 0
        while (r < &h)
            c = 0
            while (c < &w)
                top-idx = ((r * &w) + c)
                bot-idx = (((r + 1) * &w) + c)
#                 rgb-to-term-fg (&p top-idx)
#                 rgb-to-term-bg (&p bot-idx)
#                 rgb-to-term-fg 0
#                 rgb-to-term-bg 0
#                 print (rgb-to-term-fg (&p top-idx))
#                 print (rgb-to-term-bg (&p bot-idx))
#                 print "▀"
                c += 1
#             print "\e[0m\n"
            r += 2

# print "resize\n"
resize screen 64 64

# print "set-pixel\n"
set-pixel screen 1 1 0xff0000

display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
display-real screen
